routes/admin.php
<?php


use App\Http\Controllers\Admin\AdsController;
use App\Http\Controllers\Admin\AssetsController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CccamServerController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\InboxController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PackageServerController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => 'admin', 'middleware' => ['auth','isAdmin'],'as' => 'admin.'], function (){

        Route::get('/', [HomeController::class, 'index'])->name('dashboard');

        Route::group(['prefix' => 'assets', 'as' => 'assets.'], function (){
            Route::get('/index', [AssetsController::class, 'index'])->name('index');
            Route::get('/create', [AssetsController::class, 'create'])->name('create');
            Route::post('/store', [AssetsController::class, 'store'])->name('store');
            Route::get('/edit/{asset}', [AssetsController::class, 'edit'])->name('edit');
            Route::put('/update', [AssetsController::class, 'update'])->name('update');
            Route::delete('/delete', [AssetsController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'sliders', 'as' => 'slider.'], function (){
            Route::get('/index', [SliderController::class, 'index'])->name('index');
            Route::get('/create', [SliderController::class, 'create'])->name('create');
            Route::post('/store', [SliderController::class, 'store'])->name('store');
            Route::get('/edit/{slider}', [SliderController::class, 'edit'])->name('edit');
            Route::put('/update', [SliderController::class, 'update'])->name('update');
            Route::delete('/delete/{slider}', [SliderController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'banners', 'as' => 'banner.'], function (){
            Route::get('/index', [BannerController::class, 'index'])->name('index');
            Route::get('/create', [BannerController::class, 'create'])->name('create');
            Route::post('/store', [BannerController::class, 'store'])->name('store');
            Route::get('/edit/{banner}', [BannerController::class, 'edit'])->name('edit');
            Route::put('/update', [BannerController::class, 'update'])->name('update');
            Route::delete('/delete/{banner}', [BannerController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'servers', 'as' => 'server.'], function (){
            Route::get('/index', [PackageServerController::class, 'index'])->name('index');
            Route::get('/create', [PackageServerController::class, 'create'])->name('create');
            Route::post('/store', [PackageServerController::class, 'store'])->name('store');
            Route::get('/show/{server}', [PackageServerController::class, 'show'])->name('show');
            Route::get('/edit/{server}', [PackageServerController::class, 'edit'])->name('edit');
            Route::put('/update', [PackageServerController::class, 'update'])->name('update');
            Route::delete('/delete/{server}', [PackageServerController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'offers', 'as' => 'offer.'], function (){
            Route::get('/index', [OfferController::class, 'index'])->name('index');
            Route::get('/create', [OfferController::class, 'create'])->name('create');
            Route::post('/store', [OfferController::class, 'store'])->name('store');
            Route::get('/edit/{offer}', [OfferController::class, 'edit'])->name('edit');
            Route::put('/update', [OfferController::class, 'update'])->name('update');
            Route::delete('/delete/{offer}', [OfferController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function (){
            Route::get('/index', [AdsController::class, 'index'])->name('index');
            Route::get('/create', [AdsController::class, 'create'])->name('create');
            Route::post('/store', [AdsController::class, 'store'])->name('store');
            Route::get('/edit/{ads}', [AdsController::class, 'edit'])->name('edit');
            Route::put('/update', [AdsController::class, 'update'])->name('update');
            Route::delete('/delete/{ads}', [AdsController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function (){
            Route::get('/index', [BlogController::class, 'index'])->name('index');
            Route::get('/create', [BlogController::class, 'create'])->name('create');
            Route::post('/store', [BlogController::class, 'store'])->name('store');
            Route::get('/edit/{blog}', [BlogController::class, 'edit'])->name('edit');
            Route::put('/update', [BlogController::class, 'update'])->name('update');
            Route::delete('/delete/{blog}', [BlogController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'review', 'as' => 'review.'], function (){
            Route::get('/index', [ReviewController::class, 'index'])->name('index');
            Route::get('/unread', [ReviewController::class, 'unread'])->name('unread');
            Route::post('/store', [ReviewController::class, 'store'])->name('store');
            Route::put('/update/{review}', [ReviewController::class, 'update'])->name('update');
            Route::delete('/delete/{review}', [ReviewController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/index', [ProfileController::class, 'index'])->name('index');
            Route::put('/update', [ProfileController::class, 'update'])->name('update');
            Route::get('/change-password', [ProfileController::class, 'passwordPage'])->name('passwordPage');
            Route::put('/change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'messages', 'as' => 'message.'], function () {
            Route::get('/index', [InboxController::class, 'index'])->name('index');
            Route::get('/deleted-massages', [InboxController::class, 'deletedMessages'])->name('deleted-massages');
            Route::get('/replay/{message}', [InboxController::class, 'repalyToUserPage'])->name('repaly-to-user-page');
            Route::post('/replay', [InboxController::class, 'repalyToUser'])->name('repaly-to-user');
            Route::get('/show/{message}', [InboxController::class, 'show'])->name('show');
            Route::delete('/delete/{message}', [InboxController::class, 'delete'])->name('delete');
            Route::delete('/soft-delete/{message}', [InboxController::class, 'softDelete'])->name('soft-delete');
            Route::get('/restore-messages/{id}', [InboxController::class, 'restoreDeletedMeassges'])->name('restore-deleted-message');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'contacts', 'as' => 'mail.'], function () {
            Route::get('/index', [ContactController::class, 'index'])->name('index');
            Route::get('/show/{contact}', [ContactController::class, 'show'])->name('show-contact');
            Route::delete('/delete/{contact}', [ContactController::class, 'delete'])->name('delete-contact');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
            Route::get('/index', [UserController::class, 'index'])->name('index');
            Route::get('/show/profile/{user}', [UserController::class, 'show'])->name('show-user');
            Route::get('/edit/{user}', [UserController::class, 'edit'])->name('edit-user');
            Route::get('/create', [UserController::class, 'create'])->name('create');

routes/user.php
<?php


use App\Http\Controllers\User\ChangePasswordController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\InboxController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\ReviewController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => 'user', 'as' => 'users.', 'middleware' => 'auth'], function () {

        Route::get('/index', [HomeController::class, 'index'])->name('home');
        /***=====================================================================***/
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
           Route::get('/index', [ProfileController::class, 'index'])->name('index');
           Route::put('/update', [ProfileController::class, 'update'])->name('update');
        });
        /***=====================================================================***/
        Route::group(['prefix' => 'messages', 'as' => 'message.'], function () {
            Route::get('/index', [InboxController::class, 'index'])->name('index');
            Route::get('/show/{message}', [InboxController::class, 'show'])->name('show');
            Route::get('/sendMessage', [InboxController::class, 'sendMessagePage'])->name('send-message-page');
            Route::post('/sendMessage', [InboxController::class, 'sendMessage'])->name('send-message');
        });
        /***=====================================================================***/
        Route::group(['prefix' => 'change-password', 'as' => 'password.'], function () {
           Route::get('/index', [ChangePasswordController::class, 'index'])->name('index');
           Route::put('/update/{user}', [ChangePasswordController::class, 'update'])->name('update');
        });
        /*--------------------Review-------------------------*/
        Route::group(['prefix' => 'review', 'as' => 'review.'], function (){
            Route::get('/', [ReviewController::class, 'index'])->name('index');
            Route::post('/store', [ReviewController::class, 'store'])->name('store');
        });
    });

});

routes/web.php
<?php

use App\Http\Controllers\EndUser\AuthController;
use App\Http\Controllers\EndUser\BlogController;
use App\Http\Controllers\EndUser\CccamServerController;
use App\Http\Controllers\EndUser\ContactController;
use App\Http\Controllers\EndUser\FacebookController;
use App\Http\Controllers\EndUser\GoogleController;
use App\Http\Controllers\EndUser\HomeController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => '/', 'as' => 'user.'], function (){
        Route::get('/index', [HomeController::class, 'index'])->name('index');
        /*--------------------ContactUs-------------------------*/
        Route::group(['prefix' => 'contact', 'as' => 'contact.'], function (){
            Route::get('/', [ContactController::class, 'index'])->name('index');
            Route::post('/send-message', [ContactController::class, 'sendMessage'])->name('send-message');
        });
        /*--------------------Blogs-------------------------*/
        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function (){
            Route::get('/blogs', [BlogController::class, 'index'])->name('index');
            Route::get('/show/{blog}', [BlogController::class, 'show'])->name('show');
        });
        /*--------------------Blogs-------------------------*/
        Route::group(['prefix' => 'cccam', 'as' => 'cccam.'], function (){
            Route::get('/packages', [CccamServerController::class, 'index'])->name('index');
        });
        /*--------------------LogOut--------------------------*/
        Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
        /*--------------------Privacy-Policy-----------------*/
        Route::get('/privacy-policy', function (){
           return view('EndUser.privacy');
        })->name('privacy');
    });
    /*---------Auth------------*/
    Route::get('/auth', [AuthController::class, 'authPage'])->name('auth');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    Route::get('/register', [AuthController::class, 'registerPage'])->name('registerPage');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/forget-password', [AuthController::class, 'forgetPasswordPage'])->name('forget-password-page');
    Route::post('/forget-password', [AuthController::class, 'forgetPassword'])->name('forget-password');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetPasswordPage'])->name('reset-password-page');
    Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('reset-password');
    /*---------facebook-login------------*/
    Route::get('/auth/facebook-redirect', [FacebookController::class, 'handleFacebookRedirect'])->name('handle-facebook-redirect');
    Route::get('/auth/facebook-callback', [FacebookController::class, 'handleFacebookCallback'])->name('handle-facebook-callbackt');
    /*---------google-login------------*/
    Route::get('/auth/google-redirect', [GoogleController::class, 'handleGoogleRedirect'])->name('handle-google-redirect');
    Route::get('/auth/google-callback', [GoogleController::class, 'handleGoogleCallback'])->name('handle-google-callbackt');


});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Interfaces\Admin\UserInterface;
use App\Http\Requests\Admin\User\UserRequest;
use App\Models\User;

class UserController extends Controller
{
    private $userInterface;

    public function __construct(UserInterface $user)
    {
        $this->userInterface = $user;
    }

    public function index()
    {
        return $this->userInterface->index();
    }

    public function show(User $user)
    {
        return $this->userInterface->show($user);
    }

    public function create()
    {
        return $this->userInterface->addNewUserPage();
    }

    public function store(UserRequest $request)
    {
        return $this->userInterface->addNewUser($request);
    }

    public function edit(User $user)
    {
        return $this->userInterface->editUser($user);
    }

    public function update(User $user, UserRequest $request)
    {
        return $this->userInterface->updateUser($user, $request);
    }

    public function delete(User $user)
    {
        return $this->userInterface->delete($user);
    }
}

resources/views/User/layouts/header.blade.php
<div class="main-header sticky side-header nav nav-item">
    <div class="container-fluid">
        <div class="main-header-left ">
            <div class="responsive-logo">
                <a href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/logo.png')}}" class="logo-1" alt="logo"></a>
                <a href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/logo-white.png')}}" class="dark-logo-1" alt="logo"></a>
                <a href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/favicon.png')}}" class="logo-2" alt="logo"></a>
                <a href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/favicon.png')}}" class="dark-logo-2" alt="logo"></a>
            </div>
            <div class="app-sidebar__toggle" data-toggle="sidebar">
                <a class="open-toggle" href="#"><i class="header-icon fe fe-align-left" ></i></a>
                <a class="close-toggle" href="#"><i class="header-icons fe fe-x"></i></a>
            </div>
        </div>
        <div class="main-header-right">
            <ul class="nav">
                <li class="">
                    <div class="dropdown  nav-itemd-none d-md-flex">
                        <a href="#" class="d-flex  nav-item nav-link pr-0 country-flag1" data-toggle="dropdown" aria-expanded="false">
                            <span class="avatar country-Flag mr-0 align-self-center {{ app()->getLocale() == 'ar' ? 'bg-light ' : 'bg-white'}}"><img src="{{URL::asset('assetsAdmin/shared/img/flags/language.svg')}}" width="256px" height="256px" alt="language" title="language"></span>
                        </a>
                        @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                            <a rel="alternate" hreflang="{{ $localeCode }}"
                               href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                                @if($properties['native']=="English")
                        <div class="dropdown-menu dropdown-menu-left dropdown-menu-arrow" x-placement="bottom-end">
                            <a href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" class="dropdown-item d-flex ">
                                <span class="avatar  mr-3 align-self-center bg-transparent"><img src="{{URL::asset('assetsAdmin/shared/img/flags/us_flag.jpg')}}" alt="img"></span>
                                <div class="d-flex">
                                    <span class="mt-2">English</span>
                                </div>
                            </a>
                            @elseif($properties['native']=="العربية")
                            <a href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" class="dropdown-item d-flex">
                                <span class="avatar  mr-3 align-self-center bg-transparent"><img src="{{URL::asset('assetsAdmin/shared/img/flags/egypt.png')}}" alt="img"></span>
                                <div class="d-flex">
                                    <span class="mt-2">Arabic</span>
                                </div>
                            </a>
                            @endif
                            @endforeach
                        </div>
                    </div>
                </li>
            </ul>
            <div class="nav nav-item  navbar-nav-right ml-auto">
                <div class="nav-link" id="bs-example-navbar-collapse-1">
                    <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="input-group-btn">
                                <button type="reset" class="btn btn-default">
                                    <i class="fas fa-times"></i>
                                </button>
                                <button type="submit" class="btn btn-default nav-link resp-btn">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="header-icon-svgs" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
                <div class="dropdown nav-item main-header-message ">
                    <a class="new nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" class="header-icon-svgs" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg><span class="{{ (count($userMessages) > 0) ? 'pulse-danger' : ''}}"></span></a>
                    <div class="dropdown-menu">
                        <div class="menu-header-content bg-primary text-left">
                            <div class="d-flex">
                                <h6 class="dropdown-title mb-1 tx-15 text-white font-weight-semibold">{{ trans('user/home.Messages') }}</h6>
                                <span class="badge badge-pill badge-warning ml-auto my-auto float-right">{{ trans('user/home.unread messages') }}</span>
                            </div>
                            <p class="dropdown-title-text subtext mb-0 text-white op-6 pb-0 tx-12 ">{{ trans('user/home.You have') }} {{ $userMessages->count() }} {{ trans('user/home.unread messages') }}</p>
                        </div>
                        <div class="main-message-list chat-scroll">
                            @forelse($userMessages as $message)
                                <a href="#" class="p-3 d-flex border-bottom">
                                    <div class="  drop-img  cover-image  " data-image-src="{{ isset($message->sender->userProfile->image) ?  $message->sender->userProfile->image : URL::asset('assetsAdmin/shared/img/faces/3.jpg') }}">
                                        <span class="avatar-status bg-teal"></span>
                                    </div>
                                    <div class="wd-90p">
                                        <div class="d-flex">
                                            <h5 class="mb-1 name">{{ $message->sender->roles->role->name  }}</h5>
                                        </div>
                                        <p class="mb-0 desc">{{ $message->message->title }}</p>
                                        <p class="time mb-0 text-left float-left ml-2 mt-2">{{ $message->created_at->format("d/m/y  H:i A") }}</p>
                                    </div>
                                </a>
                            @empty
                            @endforelse

                        </div>
                        <div class="text-center dropdown-footer">
                            <a href="{{ route('users.message.index') }}">{{ trans('user/home.VIEW ALL') }}</a>
                        </div>
                    </div>
                </div>

                <div class="nav-item full-screen fullscreen-button">
                    <a class="new nav-link full-screen-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" class="header-icon-svgs" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-maximize"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path></svg></a>
                </div>
                <div class="dropdown main-profile-menu nav nav-item nav-link">
                    <a class="profile-user d-flex" href=""><img alt="" src="{{URL::asset('assetsAdmin/shared/img/faces/6.jpg')}}"></a>
                    <div class="dropdown-menu">
                        <div class="main-header-profile bg-primary p-3">
                            <div class="d-flex wd-100p">
                                <div class="main-img-user"><img alt="" src="{{URL::asset('assetsAdmin/shared/img/faces/6.jpg')}}" class=""></div>
                                <div class="ml-3 my-auto">
                                    <h6>{{ Auth::user()->name }}</h6><span>{{ trans('user/home.client') }}</span>
                                </div>
                            </div>
                        </div>
                        <a class="dropdown-item" href="{{ route('users.profile.index') }}"><i class="bx bx-user-circle"></i>{{ trans('user/home.Profile') }}</a>
                        <a class="dropdown-item" href="{{ route('users.password.index') }}"><i class="bx bx-key"></i> {{ trans('user/home.Change-Password') }}</a>
                        <form method="post" action="{{route('user.logout')}}">
                            @csrf
                            <button class="dropdown-item" type="submit"><i class="bx bx-log-out"></i> {{ trans('user/home.Sign Out') }}</button>
                        </form>
                    </div>
                </div>
                <div class="dropdown main-header-message right-toggle">
                    <a class="nav-link pr-0" data-toggle="sidebar-right" data-target=".sidebar-right">
                        <svg xmlns="http://www.w3.org/2000/svg" class="header-icon-svgs" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/User/layouts/main-sidebar.blade.php
<!-- main-sidebar -->
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar sidebar-scroll">
    <div class="main-sidebar-header active">
        <a class="desktop-logo logo-light active" href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/logo.png')}}" class="main-logo" alt="logo"></a>
        <a class="desktop-logo logo-dark active" href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/logo-white.png')}}" class="main-logo dark-theme" alt="logo"></a>
        <a class="logo-icon mobile-logo icon-light active" href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/favicon.png')}}" class="logo-icon" alt="logo"></a>
        <a class="logo-icon mobile-logo icon-dark active" href="#"><img src="{{URL::asset('assetsAdmin/shared/img/brand/favicon-white.png')}}" class="logo-icon dark-theme" alt="logo"></a>
    </div>
    <div class="main-sidemenu">
        <div class="app-sidebar__user clearfix">
            <div class="dropdown user-pro-body">
                <div class="">
                    <img alt="user-img" class="avatar avatar-xl brround" src="{{isset(auth()->user()->profileUser()->image)? auth()->user()->profileUser()->image : URL::asset('assetsAdmin/shared/img/faces/6.jpg')}}"><span class="avatar-status profile-status bg-green"></span>
                </div>
                <div class="user-info">
                    <h4 class="font-weight-semibold mt-3 mb-0">{{ ucwords(Auth::user()->name) }}</h4>
                    <span class="mb-0 text-muted font-weight-bolder">{{ (auth()->user()->roles->role->name == 'user') ? trans('user/sidebar.user') : trans('user/sidebar.admin') }}</span>
                </div>
            </div>
        </div>
        <ul class="side-menu">
            <li class="side-item side-item-category">{{ trans('user/sidebar.main') }}</li>
            <li class="slide">
                <a class="side-menu__item" href="{{ route('users.home') }}" target="_self"><svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" viewBox="0 0 24 24" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M5 5h4v6H5zm10 8h4v6h-4zM5 17h4v2H5zM15 5h4v2h-4z" opacity=".3"/><path d="M3 13h8V3H3v10zm2-8h4v6H5V5zm8 16h8V11h-8v10zm2-8h4v6h-4v-6zM13 3v6h8V3h-8zm6 4h-4V5h4v2zM3 21h8v-6H3v6zm2-4h4v2H5v-2z"/></svg><span class="side-menu__label">{{ trans('user/sidebar.dashboard') }}</span></a>
                <a class="side-menu__item" href="{{ route('user.index') }}" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" viewBox="0 0 24 24" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M5 5h4v6H5zm10 8h4v6h-4zM5 17h4v2H5zM15 5h4v2h-4z" opacity=".3"/><path d="M3 13h8V3H3v10zm2-8h4v6H5V5zm8 16h8V11h-8v10zm2-8h4v6h-4v-6zM13 3v6h8V3h-8zm6 4h-4V5h4v2zM3 21h8v-6H3v6zm2-4h4v2H5v-2z"/></svg><span class="side-menu__label">{{ trans('user/sidebar.site') }}</span></a>
            </li>

            <li class="side-item side-item-category">{{ trans('user/sidebar.sitting') }}</li>
            <li class="slide">
                <a class="side-menu__item" data-toggle="slide" href="#"><svg xmlns="http://www.w3.org/2000/svg" class="side-menu__icon" viewBox="0 0 24 24" ><path d="M0 0h24v24H0V0z" fill="none"/><path d="M15 11V4H4v8.17l.59-.58.58-.59H6z" opacity=".3"/><path d="M21 6h-2v9H6v2c0 .55.45 1 1 1h11l4 4V7c0-.55-.45-1-1-1zm-5 7c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1v14l4-4h10zM4.59 11.59l-.59.58V4h11v7H5.17l-.58.59z"/></svg><span class="side-menu__label">{{ trans('user/sidebar.Messages') }}</span><i class="angle fe fe-chevron-down"></i></a>
                <ul class="slide-menu">
                    <li><a class="slide-item" href="{{ route('users.message.index') }}">{{ trans('user/sidebar.InBox') }}</a></li>
                    <li><a class="slide-item" href="{{ route('users.message.send-message') }}">{{ trans('user/sidebar.Send Message') }}</a></li>
                </ul>
            </li>


        </ul>
    </div>
</aside>
<!-- main-sidebar -->