routes/admin.php
<?php


use App\Http\Controllers\Admin\AdsController;
use App\Http\Controllers\Admin\AssetsController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CccamServerController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\InboxController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PackageServerController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => 'admin', 'middleware' => ['auth','isAdmin'],'as' => 'admin.'], function (){

        Route::get('/', [HomeController::class, 'index'])->name('dashboard');

        Route::group(['prefix' => 'assets', 'as' => 'assets.'], function (){
            Route::get('/index', [AssetsController::class, 'index'])->name('index');
            Route::get('/create', [AssetsController::class, 'create'])->name('create');
            Route::post('/store', [AssetsController::class, 'store'])->name('store');
            Route::get('/edit/{asset}', [AssetsController::class, 'edit'])->name('edit');
            Route::put('/update', [AssetsController::class, 'update'])->name('update');
            Route::delete('/delete', [AssetsController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'sliders', 'as' => 'slider.'], function (){
            Route::get('/index', [SliderController::class, 'index'])->name('index');
            Route::get('/create', [SliderController::class, 'create'])->name('create');
            Route::post('/store', [SliderController::class, 'store'])->name('store');
            Route::get('/edit/{slider}', [SliderController::class, 'edit'])->name('edit');
            Route::put('/update', [SliderController::class, 'update'])->name('update');
            Route::delete('/delete/{slider}', [SliderController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'banners', 'as' => 'banner.'], function (){
            Route::get('/index', [BannerController::class, 'index'])->name('index');
            Route::get('/create', [BannerController::class, 'create'])->name('create');
            Route::post('/store', [BannerController::class, 'store'])->name('store');
            Route::get('/edit/{banner}', [BannerController::class, 'edit'])->name('edit');
            Route::put('/update', [BannerController::class, 'update'])->name('update');
            Route::delete('/delete/{banner}', [BannerController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'servers', 'as' => 'server.'], function (){
            Route::get('/index', [PackageServerController::class, 'index'])->name('index');
            Route::get('/create', [PackageServerController::class, 'create'])->name('create');
            Route::post('/store', [PackageServerController::class, 'store'])->name('store');
            Route::get('/show/{server}', [PackageServerController::class, 'show'])->name('show');
            Route::get('/edit/{server}', [PackageServerController::class, 'edit'])->name('edit');
            Route::put('/update', [PackageServerController::class, 'update'])->name('update');
            Route::delete('/delete/{server}', [PackageServerController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'offers', 'as' => 'offer.'], function (){
            Route::get('/index', [OfferController::class, 'index'])->name('index');
            Route::get('/create', [OfferController::class, 'create'])->name('create');
            Route::post('/store', [OfferController::class, 'store'])->name('store');
            Route::get('/edit/{offer}', [OfferController::class, 'edit'])->name('edit');
            Route::put('/update', [OfferController::class, 'update'])->name('update');
            Route::delete('/delete/{offer}', [OfferController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function (){
            Route::get('/index', [AdsController::class, 'index'])->name('index');
            Route::get('/create', [AdsController::class, 'create'])->name('create');
            Route::post('/store', [AdsController::class, 'store'])->name('store');
            Route::get('/edit/{ads}', [AdsController::class, 'edit'])->name('edit');
            Route::put('/update', [AdsController::class, 'update'])->name('update');
            Route::delete('/delete/{ads}', [AdsController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function (){
            Route::get('/index', [BlogController::class, 'index'])->name('index');
            Route::get('/create', [BlogController::class, 'create'])->name('create');
            Route::post('/store', [BlogController::class, 'store'])->name('store');
            Route::get('/edit/{blog}', [BlogController::class, 'edit'])->name('edit');
            Route::put('/update', [BlogController::class, 'update'])->name('update');
            Route::delete('/delete/{blog}', [BlogController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'review', 'as' => 'review.'], function (){
            Route::get('/index', [ReviewController::class, 'index'])->name('index');
            Route::get('/unread', [ReviewController::class, 'unread'])->name('unread');
            Route::post('/store', [ReviewController::class, 'store'])->name('store');
            Route::put('/update/{review}', [ReviewController::class, 'update'])->name('update');
            Route::delete('/delete/{review}', [ReviewController::class, 'destroy'])->name('destroy');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/index', [ProfileController::class, 'index'])->name('index');
            Route::put('/update', [ProfileController::class, 'update'])->name('update');
            Route::get('/change-password', [ProfileController::class, 'passwordPage'])->name('passwordPage');
            Route::put('/change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'messages', 'as' => 'message.'], function () {
            Route::get('/index', [InboxController::class, 'index'])->name('index');
            Route::get('/deleted-massages', [InboxController::class, 'deletedMessages'])->name('deleted-massages');
            Route::get('/replay/{message}', [InboxController::class, 'repalyToUserPage'])->name('repaly-to-user-page');
            Route::post('/replay', [InboxController::class, 'repalyToUser'])->name('repaly-to-user');
            Route::get('/show/{message}', [InboxController::class, 'show'])->name('show');
            Route::delete('/delete/{message}', [InboxController::class, 'delete'])->name('delete');
            Route::delete('/soft-delete/{message}', [InboxController::class, 'softDelete'])->name('soft-delete');
            Route::get('/restore-messages/{id}', [InboxController::class, 'restoreDeletedMeassges'])->name('restore-deleted-message');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'contacts', 'as' => 'mail.'], function () {
            Route::get('/index', [ContactController::class, 'index'])->name('index');
            Route::get('/show/{contact}', [ContactController::class, 'show'])->name('show-contact');
            Route::delete('/delete/{contact}', [ContactController::class, 'delete'])->name('delete-contact');
        });
        /***-------------------------------------------------------------------------------***/
        Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
            Route::get('/index', [UserController::class, 'index'])->name('index');
            Route::get('/show/profile/{user}', [UserController::class, 'show'])->name('show-user');
            Route::get('/edit/{user}', [UserController::class, 'edit'])->name('edit-user');
            Route::get('/create', [UserController::class, 'create'])->name('create');

routes/user.php
<?php


use App\Http\Controllers\User\ChangePasswordController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\InboxController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\ReviewController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => 'user', 'as' => 'users.', 'middleware' => 'auth'], function () {

        Route::get('/index', [HomeController::class, 'index'])->name('home');
        /***=====================================================================***/
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
           Route::get('/index', [ProfileController::class, 'index'])->name('index');
           Route::put('/update', [ProfileController::class, 'update'])->name('update');
        });
        /***=====================================================================***/
        Route::group(['prefix' => 'messages', 'as' => 'message.'], function () {
            Route::get('/index', [InboxController::class, 'index'])->name('index');
            Route::get('/show/{message}', [InboxController::class, 'show'])->name('show');
            Route::get('/sendMessage', [InboxController::class, 'sendMessagePage'])->name('send-message-page');
            Route::post('/sendMessage', [InboxController::class, 'sendMessage'])->name('send-message');
        });
        /***=====================================================================***/
        Route::group(['prefix' => 'change-password', 'as' => 'password.'], function () {
           Route::get('/index', [ChangePasswordController::class, 'index'])->name('index');
           Route::put('/update/{user}', [ChangePasswordController::class, 'update'])->name('update');
        });
        /*--------------------Review-------------------------*/
        Route::group(['prefix' => 'review', 'as' => 'review.'], function (){
            Route::get('/', [ReviewController::class, 'index'])->name('index');
            Route::post('/store', [ReviewController::class, 'store'])->name('store');
        });
    });

});

routes/web.php
<?php

use App\Http\Controllers\EndUser\AuthController;
use App\Http\Controllers\EndUser\BlogController;
use App\Http\Controllers\EndUser\CccamServerController;
use App\Http\Controllers\EndUser\ContactController;
use App\Http\Controllers\EndUser\FacebookController;
use App\Http\Controllers\EndUser\GoogleController;
use App\Http\Controllers\EndUser\HomeController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){

    Route::group(['prefix' => '/', 'as' => 'user.'], function (){
        Route::get('/index', [HomeController::class, 'index'])->name('index');
        /*--------------------ContactUs-------------------------*/
        Route::group(['prefix' => 'contact', 'as' => 'contact.'], function (){
            Route::get('/', [ContactController::class, 'index'])->name('index');
            Route::post('/send-message', [ContactController::class, 'sendMessage'])->name('send-message');
        });
        /*--------------------Blogs-------------------------*/
        Route::group(['prefix' => 'blog', 'as' => 'blog.'], function (){
            Route::get('/blogs', [BlogController::class, 'index'])->name('index');
            Route::get('/show/{blog}', [BlogController::class, 'show'])->name('show');
        });
        /*--------------------Blogs-------------------------*/
        Route::group(['prefix' => 'cccam', 'as' => 'cccam.'], function (){
            Route::get('/packages', [CccamServerController::class, 'index'])->name('index');
        });
        /*--------------------LogOut--------------------------*/
        Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
        /*--------------------Privacy-Policy-----------------*/
        Route::get('/privacy-policy', function (){
           return view('EndUser.privacy');
        })->name('privacy');
    });
    /*---------Auth------------*/
    Route::get('/auth', [AuthController::class, 'authPage'])->name('auth');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    Route::get('/register', [AuthController::class, 'registerPage'])->name('registerPage');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/forget-password', [AuthController::class, 'forgetPasswordPage'])->name('forget-password-page');
    Route::post('/forget-password', [AuthController::class, 'forgetPassword'])->name('forget-password');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetPasswordPage'])->name('reset-password-page');
    Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('reset-password');
    /*---------facebook-login------------*/
    Route::get('/auth/facebook-redirect', [FacebookController::class, 'handleFacebookRedirect'])->name('handle-facebook-redirect');
    Route::get('/auth/facebook-callback', [FacebookController::class, 'handleFacebookCallback'])->name('handle-facebook-callbackt');
    /*---------google-login------------*/
    Route::get('/auth/google-redirect', [GoogleController::class, 'handleGoogleRedirect'])->name('handle-google-redirect');
    Route::get('/auth/google-callback', [GoogleController::class, 'handleGoogleCallback'])->name('handle-google-callbackt');


});

resources/views/Admin/servers/index.blade.php
@extends('Admin.layouts.master')

@section('title')
    {{ trans('admin/package-server.PackageServers') }}
@endsection


@section('content')
    <div class="container-fluid">

        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
            <div class="my-auto">
                <div class="d-flex">
                    <h4 class="content-title mb-0 my-auto"><a href="{{ route('admin.dashboard') }}">{{ trans('admin/package-server.Dashboard') }} / </a></h4>
                    <span class="text-muted mt-1 tx-13 ml-2 mb-0"><a href="{{ route('admin.server.index') }}"><h5 class="text-white-50">{{ trans('admin/package-server.PackageServers') }} /</h5></a> </span>
                    <span class="text-muted mt-1 tx-13 ml-2 mb-0"><a href="{{ route('admin.server.create') }}"><h5 class="text-white-50">{{ trans('admin/package-server.Add New Package') }}</h5></a> </span>
                </div>
            </div>
            <div class="d-flex my-xl-auto right-content">
                <div class="mb-3 mb-xl-0">
                    <div class="btn-group dropdown">
                        <button type="button" class="btn btn-primary">{{ date('d,m,Y') }}</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb -->
        <div class="col-xl-12">
            <div class="card mg-b-20">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title mg-b-0">{{ trans('admin/package-server.PackageServers') }}</h4>
                        <a href="{{ route('admin.server.create') }}" class="btn btn-warning-gradient">{{ trans('admin/package-server.Add New Package') }}</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example" class="table key-buttons text-md-nowrap">
                            <thead>
                            <tr>
                                <th class="border-bottom-0 text-center">{{ trans('admin/package-server.server') }}</th>
                                <th class="border-bottom-0 text-center">{{ trans('admin/package-server.price') }}</th>
                                <th class="border-bottom-0 text-center">{{ trans('admin/action.Action') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($servers) && $servers->count() > 0)
                                @foreach($servers as $server)
                                    <tr>
                                        <td class="text-center"><a href="{{ route('admin.server.show', $server) }}" >{{ $server->name }}</a></td>
                                        <td class="text-center">{{ $server->price }} $</td>
                                        <td class="text-center">
                                            <div class="dropdown">
                                                <button aria-expanded="false" aria-haspopup="true" class="btn ripple btn-info-gradient"
                                                        data-toggle="dropdown" type="button">Choose Action<i class="fas fa-caret-down ml-1"></i></button>
                                                <div class="dropdown-menu tx-13">
                                                    <a class="dropdown-item" href="{{ route('admin.server.edit', $server) }}">{{ trans('admin/action.Edit') }}</a>

                                                    <form action="{{ route('admin.server.destroy', $server) }}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <input type="hidden" name="server_id" value="{{ $server->id }}">
                                                        <button type="submit" class="dropdown-item">{{ trans('admin/action.Delete') }}</button>
                                                    </form>

                                                </div>
                                            </div>

                                        </td>

                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <!-- Internal Data tables -->
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jquery.dataTables.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jszip.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/pdfmake.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/vfs_fonts.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.html5.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.print.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/responsive.bootstrap4.min.js')}}"></script>

    <!--Internal  Datatable js -->
    <script src="{{ URL::asset('assetsAdmin/shared/js/table-data.js')}}"></script>
@endsection

resources/views/Admin/servers/show.blade.php
@extends('Admin.layouts.master')

@section('title')
    {{ $server->name }}
@endsection

@section('css')
    <!-- Internal Data table css -->
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" />
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/datatable/css/responsive.bootstrap4.min.css')}}" rel="stylesheet" />
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/datatable/css/jquery.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/datatable/css/responsive.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/select2/css/select2.min.css')}}" rel="stylesheet">

    <!--  Right-sidemenu css -->
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/sidebar/sidebar.css')}}" rel="stylesheet">

    <!--  Custom Scroll bar-->
    <link href="{{ URL::asset('assetsAdmin/shared/plugins/mscrollbar/jquery.mCustomScrollbar.css')}}" rel="stylesheet"/>

    <!--  Left-Sidebar css -->
    <link rel="stylesheet" href="{{ URL::asset('assetsAdmin/en/css/sidemenu.css')}}">

    <!--- Style css --->
    <link href="{{ URL::asset('assetsAdmin/en/css/style.css')}}" rel="stylesheet">

    <!--- Dark-mode css --->
    <link href="{{ URL::asset('assetsAdmin/en/css/style-dark.css')}}" rel="stylesheet">

    <!---Skinmodes css-->
    <link href="{{ URL::asset('assetsAdmin/en/css/skin-modes.css')}}" rel="stylesheet" />

    <!--- Animations css-->
    <link href="{{ URL::asset('assetsAdmin/en/css/animate.css')}}" rel="stylesheet">

    <link href="{{ URL::asset('assetsAdmin/en/css/icons.css')}}" rel="stylesheet">

@endsection

@section('content')
    <div class="container-fluid">

        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
            <div class="my-auto">
                <div class="d-flex">
                    <h4 class="content-title mb-0 my-auto"><a href="{{ route('admin.dashboard') }}">{{ trans('admin/package-server.Dashboard') }} / </a></h4>
                    <span class="text-muted mt-1 tx-13 ml-2 mb-0"><a href="{{ route('admin.server.index') }}"><h5 class="text-white-50">{{ trans('admin/package-server.PackageServers') }} /</h5></a> </span>
                    <span class="text-muted mt-1 tx-13 ml-2 mb-0"><a href="{{ route('admin.server.show', $server) }}"><h5 class="text-white-50">{{ $server->name }}</h5></a> </span>
                </div>
            </div>
            <div class="d-flex my-xl-auto right-content">
                <div class="mb-3 mb-xl-0">
                    <div class="btn-group dropdown">
                        <button type="button" class="btn btn-primary">{{ date('d,m,Y') }}</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb -->
        <div class="col-xl-12">
            <div class="card mg-b-20">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between">
                        <h4 class="card-title mg-b-0">{{ trans('admin/package-server.PackageServers') }}</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12  col-lg-12 col-xl-4 mx-auto">
                            <div class="card card-body bg-primary ">
                                <div class="card-body">
                                    <h5 class="card-title text-white text-center">{{ $server->name }}</h5>
                                    <h6 class="card-subtitle mb-2 text-white text-center">{{ trans('admin/package-server.details') }}</h6>
                                    <p class="card-text text-center">{!! nl2br($server->details) !!}</p>
                                    <p class="card-text text-white text-center">{{ $server->price }} $ | {{ $server->duration }} {{ trans('admin/package-server.month') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <!-- Internal Data tables -->
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jquery.dataTables.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/jszip.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/pdfmake.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/vfs_fonts.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.html5.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.print.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{ URL::asset('assetsAdmin/shared/plugins/datatable/js/responsive.bootstrap4.min.js')}}"></script>

    <!--Internal  Datatable js -->
    <script src="{{ URL::asset('assetsAdmin/shared/js/table-data.js')}}"></script>
@endsection